runs:
  using: "composite"
  steps:
    - name: Install Hex
      shell: bash
      run: mix local.hex

    - name: Install Rebar3
      shell: bash
      run: mix local.rebar

    - name: Install Nerves Bootstrap
      shell: bash
      run: mix archive.install --force hex nerves_bootstrap